# Generated by Django 2.0.4 on 2018-04-27 12:02

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.CharField(blank=True, max_length=40)),
                ('first_name', models.CharField(blank=True, default='a', max_length=20)),
                ('last_name', models.CharField(blank=True, default='b', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('department_name', models.CharField(blank=True, default='a', max_length=20)),
                ('contact_usr', models.CharField(blank=True, default='a', max_length=20)),
                ('phone', models.CharField(blank=True, default='123', max_length=20)),
                ('enterprise_name', models.CharField(blank=True, default='a', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('user_management', '用户管理'), ('ibuild_management', '违建管理'), ('demolition_management', '拆迁管理'), ('recource_management', '资源管理')),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=20)),
                ('image', models.CharField(blank=True, max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=20)),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modify_time', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
