# Generated by Django 2.0.4 on 2018-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20180427_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
