# Generated by Django 2.0.4 on 2018-04-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20180428_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmap',
            name='satelite',
        ),
    ]
