# Generated by Django 2.0.4 on 2018-04-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_remove_bmap_satelite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmap',
            old_name='thumbnail_ftp',
            new_name='thumbnail_path',
        ),
        migrations.RenameField(
            model_name='bmap',
            old_name='wholemap_ftp',
            new_name='wholemap_path',
        ),
    ]
