# Generated by Django 2.0.4 on 2018-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_auto_20180428_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmap',
            name='satelite',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
