# Generated by Django 2.0.4 on 2018-04-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_bmap_satelite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buser',
            name='department_name',
        ),
        migrations.AddField(
            model_name='buser',
            name='usr_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
