# Generated by Django 2.0.4 on 2018-04-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_auto_20180430_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buser',
            options={'permissions': (('city_management', '市政管理'), ('agriculture_management', '农业管理'), ('forestry_management', '林业管理'), ('environment_management', '环境管理'), ('road_management', '道路管理'), ('settlement_observation', '沉降检测'))},
        ),
    ]
